### ISSUE TITLE
[Minor] Can't signup

### ISSUE THREAD

**Issue by FXStrato** [cue-music/cue-music#13]
I attempted to make an account with these settings:
email: abc
password: abc
confirm password: abc

clicking on submit does not do anything. I noticed these issues in the console; is any one of these causing it? 
![image](https://cloud.githubusercontent.com/assets/5132248/26799156/4d5b7bb0-49e9-11e7-96e6-923f0812e389.png)

**Comment by AlexBieg** [comment]
The error here is that a password needs to be at least 6 characters long. We have a small piece of text that says this, but did not have time to implement error handling for signup. The errors in the console are due to some trickery needed to play youtube and soundcloud audio without having visual interfaces. We would like to fix this, but since it is not in our requirements it will be a lower priority.
